### ISSUE TITLE
FileChanger output problems

### ISSUE THREAD

**Issue by staudtMarius** [ie3-institute/MobilitySimulator#34]
When using the current FileChanger implementation, the content of some files do not match the file headline.

**Comment by sebastian-peter** [comment]
You're not the first one to notice this issue :) In fact, it has been fixed in the current PSDM snapshot: https://github.com/ie3-institute/PowerSystemDataModel/pull/564

So updating PSDM to the current snapshot version `PowerSystemDataModel:3.0-SNAPSHOT` should fix this. There _might_ be new issues related to changes in PSDM then, which we would need to adapt to then.

**Comment by staudtMarius** [comment]
Updating the used PSDM version to the current snapshot version does resolve this issue. There are no other noticeable problems.
But I noticed that the methode ``changePoiFile()`` can only be used for adding ``uuids`` to an existing poi file and not for combining old poi files into one new poi file.
